import {
  VentilatorSettings,
  PatientParameters,
  MonitoredData,
  WaveformSample,
  ManeuverState,
} from '../types/ventilation';
import { audioEngine } from './audioEngine';

export function calculateIBW(heightCm: number, gender: 'male' | 'female'): number {
  const inchesOver5Ft = (heightCm - 152.4) / 2.54;
  const base = gender === 'male' ? 50 : 45.5;
  const ibw = base + 2.3 * Math.max(0, inchesOver5Ft);
  return Math.round(ibw * 10) / 10;
}

export class VentilationPhysicsEngine {
  private cycleTime: number = 0; // Current time inside the breath cycle (s)
  private totalSimulationTime: number = 0; // Global time (s)
  private currentVolume: number = 0; // mL
  private currentPressure: number = 5; // cmH2O
  private currentFlow: number = 0; // L/min
  private isInspPhase: boolean = true;
  private isPausePhase: boolean = false;
  private isExpPausePhase: boolean = false;
  private lastPeakFlow: number = 30; // L/min for PSV cycling
  private cyclePeakPressure: number = 15;
  private cyclePlateauPressure: number = 12;
  private plateauMeasuredThisCycle: boolean = false;
  private cycleVti: number = 450;
  private cycleVte: number = 440;
  private lastTriggered: boolean = false;
  private breathCounter: number = 0;
  private spontBreathCounter: number = 0;
  
  // Patient Physiological State (Dynamic)
  private currentPaCO2: number = 40;
  private currentPaO2: number = 95;
  private currentpH: number = 7.4;
  private currentSpO2: number = 98;
  
  // Committed Displayed Values (Updated strictly at breath-cycle events, not instantaneous jump)
  private displayedPeak: number = 15;
  private displayedPlat: number = 12;
  private displayedVte: number = 440;
  private displayedVti: number = 450;
  private displayedMV: number = 6.0;

  // History buffer for rolling calculations
  private rollingVte: number[] = [450, 450, 450];
  private rollingRates: number[] = [15, 15, 15];

  public reset() {
    this.cycleTime = 0;
    this.currentVolume = 0;
    this.currentPressure = 5;
    this.currentFlow = 0;
    this.isInspPhase = true;
    this.isPausePhase = false;
    this.isExpPausePhase = false;
  }

  /**
   * Generates a single physics time-step sample (typically dt = 0.0166s = 60Hz or 0.02s = 50Hz)
   */
  public step(
    dt: number,
    settings: VentilatorSettings,
    patient: PatientParameters,
    maneuvers: ManeuverState
  ): { sample: WaveformSample; monitored: MonitoredData } {
    this.totalSimulationTime += dt;
    this.cycleTime += dt;

    // Time constant tau = R * C (seconds)
    // R is cmH2O/(L/s), C is mL/cmH2O -> C in L/cmH2O = C / 1000
    const C_L = Math.max(patient.compliance, 5) / 1000;
    const Raw = Math.max(patient.resistance, 1);
    const tau = Raw * C_L;

    // Patient Spontaneous Muscular Effort Pmus(t) & Trigger Sensitivity Check
    let pmus = 0;
    let isPatientTriggering = false;
    
    // Dynamic physiological feedback (reaction to settings)
    let dynamicSpontRate = patient.spontaneousRate;
    let dynamicEffort = patient.spontaneousEffortPressure;
    
    if (patient.spontaneousDrive) {
      // Hypoxemia drives respiratory rate up
      if (this.currentSpO2 < 90) {
        dynamicSpontRate += (90 - this.currentSpO2) * 0.8;
        dynamicEffort -= 2; // Pull harder
      }
      // Hypercapnia / Acidosis drives respiratory rate and effort up
      if (this.currentPaCO2 > 45) {
        dynamicSpontRate += (this.currentPaCO2 - 45) * 0.5;
        dynamicEffort -= (this.currentPaCO2 - 45) * 0.3;
      }
      
      dynamicSpontRate = Math.min(dynamicSpontRate, 45); // Max out at 45 rpm
      dynamicEffort = Math.max(dynamicEffort, -25); // Max out at -25 cmH2O pull

      const spontCycleDuration = 60 / Math.max(dynamicSpontRate, 5);
      const spontTimeInCycle = this.totalSimulationTime % spontCycleDuration;
      const spontInspDuration = spontCycleDuration * patient.spontaneousDutyCycle;
      
      if (spontTimeInCycle < spontInspDuration) {
        // Half-sine wave for muscular inspiratory pull
        const progress = spontTimeInCycle / spontInspDuration;
        pmus = dynamicEffort * Math.sin(progress * Math.PI);

        // Check Trigger Criteria according to triggerType and triggerSensitivity:
        // Pressure trigger: patient effort must generate negative delta Paw >= triggerSensitivity (e.g., 2.0 cmH2O)
        // Flow trigger: patient effort generates inspiratory flow demand >= triggerSensitivity (e.g., 2.0 L/min)
        if (settings.triggerType === 'pressure') {
          const requiredPmus = -Math.abs(settings.triggerSensitivity || 2.0);
          if (pmus <= requiredPmus) {
            isPatientTriggering = true;
          }
        } else {
          // Flow trigger: flow generated by patient muscular effort = |Pmus| / Raw * 60 (in L/min)
          const patientInspFlowLpm = (Math.abs(pmus) / Raw) * 60;
          const flowThreshold = Math.max(0.5, settings.triggerSensitivity || 2.0);
          if (patientInspFlowLpm >= flowThreshold) {
            isPatientTriggering = true;
          }
        }
      }
    }

    // Secretion crackle / sawtooth noise in airway flow
    let secretionNoise = 0;
    if (patient.secretionsSeverity === 'mild') {
      secretionNoise = (Math.sin(this.totalSimulationTime * 45) + Math.sin(this.totalSimulationTime * 85)) * 1.8;
    } else if (patient.secretionsSeverity === 'severe') {
      secretionNoise = (Math.sin(this.totalSimulationTime * 35) + Math.sin(this.totalSimulationTime * 110) + (Math.random() - 0.5) * 3) * 4.5;
    }

    // Determine cycle timings based on mode
    let targetRR = settings.respiratoryRate;
    let inspTime = 1.0;
    let expTime = 3.0;
    let cycleDuration = 4.0;

    switch (settings.mode) {
      case 'VCV': {
        cycleDuration = 60 / Math.max(settings.respiratoryRate, 1);
        const vtL = (settings.tidalVolume || 450) / 1000; // L
        
        // In this app, Ti is controlled via inspiratoryTimePCV for both VCV and PCV.
        inspTime = settings.inspiratoryTimePCV || 1.0;
        
        // Pause time
        const pauseTime = (settings.inspiratoryPausePercent / 100) * cycleDuration;
        const totalInspWithPause = inspTime + pauseTime;
        expTime = Math.max(0.4, cycleDuration - totalInspWithPause);
        break;
      }
      case 'PCV': {
        cycleDuration = 60 / Math.max(settings.respiratoryRate, 1);
        inspTime = settings.inspiratoryTimePCV || 1.0;
        expTime = Math.max(0.4, cycleDuration - inspTime);
        break;
      }
      case 'PSV':
      case 'CPAP': {
        // Spontaneous mode governed by patient's own rate or apnea backup
        const activeRate = patient.spontaneousDrive ? dynamicSpontRate : (60 / settings.backupApneaTime);
        cycleDuration = 60 / Math.max(activeRate, 4);
        inspTime = cycleDuration * (patient.spontaneousDrive ? patient.spontaneousDutyCycle : 0.33);
        expTime = Math.max(0.4, cycleDuration - inspTime);
        break;
      }
      case 'APRV': {
        cycleDuration = settings.tHigh + settings.tLow;
        inspTime = settings.tHigh;
        expTime = settings.tLow;
        break;
      }
      case 'SIMV_VC':
      case 'SIMV_PC': {
        cycleDuration = 60 / Math.max(settings.simvRate, 4);
        inspTime = settings.inspiratoryTimePCV || 1.0;
        expTime = Math.max(0.4, cycleDuration - inspTime);
        break;
      }
    }

    // Handle Active Diagnostic Maneuvers
    const isInspiratoryHold = maneuvers.inspiratoryHoldActive;
    const isExpiratoryHold = maneuvers.expiratoryHoldActive;
    const setPeep = maneuvers.recruitmentManeuverActive ? Math.min(settings.peep + 15, 35) : settings.peep;
    const measuredRR = targetRR + (patient.spontaneousDrive ? Math.round(dynamicSpontRate * 0.6) : 0);

    // Breath Cycle State Machine
    if (this.isInspPhase) {
      if (this.cycleTime >= inspTime) {
        if (isInspiratoryHold) {
          // Stay locked in insp pause
          this.isPausePhase = true;
        } else {
          // Check if VCV has set pause percent
          const pauseDuration = settings.mode === 'VCV' ? (settings.inspiratoryPausePercent / 100) * cycleDuration : 0;
          if (this.cycleTime < inspTime + pauseDuration) {
            this.isPausePhase = true;
          } else {
            // Transition to expiration
            this.isInspPhase = false;
            this.isPausePhase = false;
            this.cycleVti = this.currentVolume;
            this.displayedVti = Math.round(this.cycleVti);
            audioEngine.playBreathExpSound(expTime, Raw);
          }
        }
      }
    } else {
      // Expiration phase: check if cycle finished OR patient triggered a new breath
      const triggerReady = this.cycleTime >= 0.25 && !isExpiratoryHold && isPatientTriggering;
      
      if ((this.cycleTime >= cycleDuration && !isExpiratoryHold) || triggerReady) {
        // End of expiration -> New breath starts!
        this.isInspPhase = true;
        this.isPausePhase = false;
        this.cycleTime = 0;
        this.cycleVte = Math.max(20, Math.round(this.cycleVti * (1 - (patient.circuitLeakPercent || 0) / 100)));
        this.displayedVte = this.cycleVte;
        this.displayedPeak = Math.round(this.cyclePeakPressure * 10) / 10;
        
        if (!this.plateauMeasuredThisCycle) {
          const calcPplat = setPeep + ((this.displayedVti / 1000) / C_L);
          // In clinical mechanics, Pplat is always strictly lower than Ppeak due to airway resistance and viscoelastic stress relaxation
          const minGap = settings.mode === 'VCV' ? 3.0 : 1.5;
          this.displayedPlat = Math.min(this.displayedPeak - minGap, Math.round(calcPplat * 10) / 10);
        } else {
          this.displayedPlat = Math.round(this.cyclePlateauPressure * 10) / 10;
        }
        
        this.displayedMV = Math.round(((this.displayedVte * measuredRR) / 1000) * 10) / 10;
        this.plateauMeasuredThisCycle = false;
        this.cyclePeakPressure = setPeep;
        this.currentVolume = 0; // reset for next breath relative baseline
        this.breathCounter++;
        
        if (isPatientTriggering || triggerReady) {
          this.spontBreathCounter++;
          this.lastTriggered = true;
          audioEngine.playTriggerSound();
        } else {
          this.lastTriggered = false;
        }
        
        audioEngine.playBreathInspSound(inspTime, settings.inspiratoryFlow || 60, Raw);
      }
    }

    // Compute Flow, Volume, and Airway Pressure Paw(t)
    let pAlveolar = (this.currentVolume / C_L) / 1000; // cmH2O above PEEP

    if (this.isInspPhase && !this.isPausePhase) {
      // INSPIRATION
      this.lastTriggered = isPatientTriggering;

      switch (settings.mode) {
        case 'VCV': {
          const vtL = (settings.tidalVolume || 450) / 1000;
          const setInspTime = settings.inspiratoryTimePCV || 1.0;
          const flowLsec = vtL / setInspTime; // Square wave (constante)

          this.currentFlow = flowLsec * 60 + secretionNoise;
          this.currentVolume += (flowLsec * 1000) * dt;
          pAlveolar = (this.currentVolume / C_L) / 1000;
          
          // Paw = PEEP + Palv + (Raw * Flow) + Pmus
          const pResistive = Raw * flowLsec;
          this.currentPressure = setPeep + pAlveolar + pResistive + pmus;
          this.lastPeakFlow = this.currentFlow;
          break;
        }

        case 'PCV': {
          const targetPinsp = setPeep + settings.inspiratoryPressure;
          const rampTime = settings.pressureRiseTime || 0.1;
          const rampProgress = Math.min(1.0, this.cycleTime / rampTime);
          const currentTargetP = setPeep + (settings.inspiratoryPressure * rampProgress);

          // Flow = (TargetP - Palv - PEEP - pmus) / Raw
          const drivingP = Math.max(0, currentTargetP - (setPeep + pAlveolar));
          const flowLsec = Math.max(0, (drivingP - pmus) / Raw);
          
          this.currentFlow = flowLsec * 60 + secretionNoise;
          this.currentVolume += (flowLsec * 1000) * dt;
          pAlveolar = (this.currentVolume / C_L) / 1000;
          
          this.currentPressure = currentTargetP + pmus;
          this.lastPeakFlow = Math.max(this.lastPeakFlow, this.currentFlow);
          break;
        }

        case 'PSV': {
          const targetPinsp = setPeep + (settings.pressureSupport || 10);
          const drivingP = Math.max(0, targetPinsp - (setPeep + pAlveolar));
          const flowLsec = Math.max(0, (drivingP - pmus) / Raw);
          
          this.currentFlow = flowLsec * 60 + secretionNoise;
          this.currentVolume += (flowLsec * 1000) * dt;
          pAlveolar = (this.currentVolume / C_L) / 1000;
          
          this.currentPressure = targetPinsp + pmus;
          this.lastPeakFlow = Math.max(this.lastPeakFlow, this.currentFlow);

          // Check Flow Cycling criterion (Esens, e.g. 25% of peak flow)
          const cycleThreshold = (settings.expiratorySensitivity / 100) * this.lastPeakFlow;
          if (this.cycleTime > 0.15 && this.currentFlow <= Math.max(cycleThreshold, 4)) {
            this.isInspPhase = false;
            this.isPausePhase = false;
            this.cycleVti = this.currentVolume;
            audioEngine.playBreathExpSound(expTime, Raw);
          }
          break;
        }

        case 'CPAP': {
          const drivingP = -pmus;
          const flowLsec = Math.max(0, drivingP / Raw);
          this.currentFlow = flowLsec * 60 + secretionNoise;
          this.currentVolume += (flowLsec * 1000) * dt;
          pAlveolar = (this.currentVolume / C_L) / 1000;
          this.currentPressure = setPeep + pmus;
          break;
        }

        case 'APRV': {
          const targetPinsp = settings.pHigh;
          const drivingP = Math.max(0, targetPinsp - (settings.pLow + pAlveolar));
          const flowLsec = Math.max(0, (drivingP - pmus) / Raw);
          this.currentFlow = flowLsec * 60 + secretionNoise;
          this.currentVolume += (flowLsec * 1000) * dt;
          pAlveolar = (this.currentVolume / C_L) / 1000;
          this.currentPressure = settings.pHigh + pmus;
          break;
        }

        case 'SIMV_VC': {
          const vtL = (settings.tidalVolume || 450) / 1000;
          const setInspTime = settings.inspiratoryTimePCV || 1.0;
          const flowLsec = vtL / setInspTime; // Square wave

          this.currentFlow = flowLsec * 60 + secretionNoise;
          this.currentVolume += (flowLsec * 1000) * dt;
          pAlveolar = (this.currentVolume / C_L) / 1000;
          
          const pResistive = Raw * flowLsec;
          this.currentPressure = setPeep + pAlveolar + pResistive + pmus;
          this.lastPeakFlow = this.currentFlow;
          break;
        }

        case 'SIMV_PC': {
          const targetPinsp = setPeep + settings.inspiratoryPressure;
          const drivingP = Math.max(0, targetPinsp - (setPeep + pAlveolar));
          const flowLsec = Math.max(0, (drivingP - pmus) / Raw);
          
          this.currentFlow = flowLsec * 60 + secretionNoise;
          this.currentVolume += (flowLsec * 1000) * dt;
          pAlveolar = (this.currentVolume / C_L) / 1000;
          
          this.currentPressure = targetPinsp + pmus;
          this.lastPeakFlow = Math.max(this.lastPeakFlow, this.currentFlow);
          break;
        }
      }

      this.cyclePeakPressure = Math.max(this.cyclePeakPressure, this.currentPressure);

    } else if (this.isPausePhase) {
      // INSPIRATORY PAUSE (Zero flow, resistive pressure drops to 0, Paw becomes Pplat)
      this.currentFlow = 0;
      pAlveolar = (this.currentVolume / C_L) / 1000;
      const minGap = settings.mode === 'VCV' ? 2.5 : 1.2;
      this.currentPressure = Math.min(this.cyclePeakPressure - minGap, setPeep + pAlveolar + pmus);
      this.cyclePlateauPressure = this.currentPressure;
      this.displayedPlat = Math.round(this.cyclePlateauPressure * 10) / 10;
      this.plateauMeasuredThisCycle = true;

    } else {
      // EXPIRATION
      const tExp = this.cycleTime - (inspTime + (settings.inspiratoryPausePercent / 100) * cycleDuration);
      
      if (isExpiratoryHold) {
        // Expiratory Hold locked -> measure Auto-PEEP
        this.currentFlow = 0;
        const autoPeepPressure = (this.currentVolume / C_L) / 1000;
        this.currentPressure = setPeep + autoPeepPressure;
      } else {
        // Passive exhalation decaying with time constant tau
        const decayFactor = Math.exp(-dt / tau);
        const expFlowLsec = -(this.currentVolume / (tau * 1000));
        
        this.currentFlow = expFlowLsec * 60 + secretionNoise;
        this.currentVolume = Math.max(0, this.currentVolume * decayFactor);
        
        pAlveolar = (this.currentVolume / C_L) / 1000;
        const pResistive = Raw * Math.abs(expFlowLsec);
        this.currentPressure = Math.max(setPeep, setPeep + pAlveolar - pResistive * 0.5) + pmus;
      }
    }

    // Circuit leak calculation
    if (patient.circuitLeakPercent && patient.circuitLeakPercent > 0) {
      const leakFactor = 1 - (patient.circuitLeakPercent / 100);
      this.currentVolume *= leakFactor;
    }

    // Compute Monitored Metrics
    const computedVte = Math.max(50, Math.round(this.cycleVti * (1 - (patient.circuitLeakPercent || 0) / 100)));
    const computedVti = Math.round(this.cycleVti);
    const minuteVentilation = (computedVte * measuredRR) / 1000; // L/min

    // Plateau estimation if no manual hold was triggered
    if (!isInspiratoryHold && this.cyclePlateauPressure === 12) {
      const calcPplat = setPeep + ((computedVti / 1000) / C_L);
      const minGap = settings.mode === 'VCV' ? 3.0 : 1.5;
      this.cyclePlateauPressure = Math.min(this.cyclePeakPressure - minGap, Math.round(calcPplat * 10) / 10);
    }

    const drivingPressure = Math.max(0, Math.round((this.cyclePlateauPressure - setPeep) * 10) / 10);
    
    // Auto-PEEP calculation based on remaining volume at end-exp
    const autoPeepCalc = Math.max(0, Math.round(((computedVti * Math.exp(-expTime / tau)) / (C_L * 1000)) * 10) / 10);
    const peepTotal = setPeep + autoPeepCalc;

    // Static and Dynamic Compliance
    const cStat = drivingPressure > 0 ? Math.round(computedVte / drivingPressure) : patient.compliance;
    const cDyn = (this.cyclePeakPressure - setPeep) > 0 ? Math.round(computedVte / (this.cyclePeakPressure - setPeep)) : patient.compliance;

    // Rapid Shallow Breathing Index (RSBI = Tobin Index = f / Vt(L))
    const rsbi = computedVte > 0 ? Math.round(measuredRR / (computedVte / 1000)) : 50;

    // Mechanical Power (J/min) = 0.098 * RR * Vt * (PIP - ΔP / 2)
    const mechanicalPower = Math.round(
      0.098 * measuredRR * (computedVte / 1000) * (this.cyclePeakPressure - (drivingPressure / 2)) * 10
    ) / 10;

    const vtPerKgIBW = Math.round((computedVte / patient.idealBodyWeightKg) * 10) / 10;

    // Arterial Blood Gas Model (Gasometria Arterial)
    const deadSpaceVol = computedVte * patient.deadSpaceFraction;
    const alveolarVentilation = Math.max(0.5, ((computedVte - deadSpaceVol) * measuredRR) / 1000); // L/min
    
    // PaCO2 inversely proportional to alveolar ventilation (normal: 40 mmHg at Va ~ 4.2 L/min)
    const basePaCO2 = (patient.metabolicRateVCO2 / alveolarVentilation) * 0.863;
    const paCO2 = Math.min(110, Math.max(18, Math.round(basePaCO2)));

    // Alveolar PO2: PAO2 = FiO2*(760-47) - PaCO2/0.8
    const effectiveFiO2 = maneuvers.o2SuctionActive ? 1.0 : settings.fio2 / 100;
    const pAlveolarO2 = effectiveFiO2 * (760 - 47) - (paCO2 / 0.8);
    
    // Shunt effect and PEEP recruitment effect on oxygenation
    const peepRecruitmentBonus = Math.min(1.0, setPeep / 15);
    const effectiveShunt = Math.max(0.04, (patient.shuntFraction / 100) * (1.2 - 0.5 * peepRecruitmentBonus));
    
    // Calculate P/F ratio based on shunt (normal 5% -> P/F ~430, ARDS 30% -> P/F ~80)
    let currentPfRatio = 500 - (effectiveShunt * 100) * 14;
    currentPfRatio = Math.max(40, Math.min(500, currentPfRatio));
    
    let calcPaO2 = currentPfRatio * effectiveFiO2;
    calcPaO2 = Math.min(pAlveolarO2 - 5, calcPaO2); // Cannot exceed Alveolar PO2
    const paO2 = Math.max(30, Math.round(calcPaO2));

    // pH via Henderson-Hasselbalch (standard HCO3 ~24 mEq/L)
    const hco3 = 24;
    const ph = Math.round((6.1 + Math.log10(hco3 / (0.0307 * paCO2))) * 100) / 100;
    const baseExcess = Math.round((hco3 - 24.8 + 16.2 * (ph - 7.4)) * 10) / 10;

    // SpO2 calculation (Severinghaus equation)
    const p50 = 26.6 * Math.pow(10, -(ph - 7.4) * 0.4); // Bohr shift
    const v = paO2 / p50;
    const spo2 = Math.min(100, Math.max(40, Math.round((Math.pow(v, 2.7) / (Math.pow(v, 2.7) + 1)) * 100)));

    const pfRatio = Math.round(paO2 / effectiveFiO2);
    const aaGradient = Math.max(5, Math.round(pAlveolarO2 - paO2));
    const etco2 = Math.round(paCO2 * (1 - patient.deadSpaceFraction * 0.4));

    // IE Ratio String
    const ieMultiplier = expTime / Math.max(inspTime, 0.1);
    const ieRatioString = `1:${ieMultiplier.toFixed(1)}`;

    const phase: WaveformSample['phase'] = this.isInspPhase 
      ? (this.isPausePhase ? 'insp_pause' : 'insp')
      : (isExpiratoryHold ? 'exp_pause' : 'exp');

    const sample: WaveformSample = {
      time: this.totalSimulationTime,
      pressure: Math.round(this.currentPressure * 10) / 10,
      flow: Math.round(this.currentFlow * 10) / 10,
      volume: Math.round(this.currentVolume),
      phase,
      isSpontaneous: isPatientTriggering,
      isTriggered: this.lastTriggered,
    };

    // Smooth internal state for dynamic response (gradual change for Gasometry and SpO2)
    const tauABG = 15.0; // ABG changes take around 15 seconds to fully adapt in UI
    const alphaABG = 1 - Math.exp(-dt / tauABG);
    this.currentPaCO2 += (paCO2 - this.currentPaCO2) * alphaABG;
    this.currentPaO2 += (paO2 - this.currentPaO2) * alphaABG;
    this.currentSpO2 += (spo2 - this.currentSpO2) * alphaABG;
    
    // pH responds instantly to the *current* smoothed PaCO2
    const currentSmoothedPh = Math.round((6.1 + Math.log10(hco3 / (0.0307 * this.currentPaCO2))) * 100) / 100;
    this.currentpH = currentSmoothedPh;

    let patientInteractionMessage = 'Paciente confortável e acoplado ao ventilador.';
    if (this.currentSpO2 < 85) {
      patientInteractionMessage = '🚨 Hipoxemia Grave: Paciente cianótico, extremidades frias, taquicardia (risco iminente).';
    } else if (this.currentSpO2 < 90) {
      patientInteractionMessage = '⚠️ Hipoxemia Leve: Paciente com desconforto, oxigenação limítrofe.';
    } else if (this.currentPaCO2 > 55 && this.currentpH < 7.25) {
      patientInteractionMessage = '🚨 Acidose Respiratória: Paciente letárgico ou com agitação psicomotora intensa (retenção de CO₂).';
    } else if (this.currentPaCO2 < 30) {
      patientInteractionMessage = '⚠️ Alcalose Respiratória: Risco de vasoconstrição cerebral por hiperventilação iatrogênica.';
    } else if (drivingPressure > 15 && this.plateauMeasuredThisCycle) {
      patientInteractionMessage = '⚠️ Risco de VILI (Lesão Pulmonar): Mecânica pulmonar estressada. Possível sobredistensão alveolar (ΔP alto).';
    } else if (autoPeepCalc > 3) {
      patientInteractionMessage = '⚠️ Alçapão Aéreo: Retenção de volume (Auto-PEEP). Risco de instabilidade hemodinâmica.';
    } else if (patient.spontaneousDrive && rsbi > 105) {
      patientInteractionMessage = '🚨 Fome de Ar: Respiração superficial e rápida (Índice de Tobin alto). Desconforto respiratório intenso.';
    } else if (settings.fio2 > 80 && this.currentSpO2 >= 96) {
      patientInteractionMessage = '⚠️ Hiperóxia: Risco de toxicidade por oxigênio. Considere desmame de FiO₂.';
    } else {
      if (patient.spontaneousDrive) {
        patientInteractionMessage = '✅ Paciente acordado, drive respiratório ativo, interagindo confortavelmente com a ventilação.';
      } else {
        patientInteractionMessage = '✅ Paciente entregue à ventilação, sem esforço, sob sedação/bloqueio adequados.';
      }
    }

    // Re-calculate derived gasometry metrics based on the SMOOTHED values
    const smoothedBaseExcess = Math.round((hco3 - 24.8 + 16.2 * (this.currentpH - 7.4)) * 10) / 10;
    const smoothedPfRatio = Math.round(this.currentPaO2 / effectiveFiO2);
    const smoothedEtCO2 = Math.round(this.currentPaCO2 * (1 - patient.deadSpaceFraction * 0.4));
    
    const monitored: MonitoredData = {
      peakPressure: Math.round(this.displayedPeak * 10) / 10,
      plateauPressure: Math.round(this.displayedPlat * 10) / 10,
      isPlateauMeasured: this.plateauMeasuredThisCycle,
      patientInteractionMessage,
      meanPressure: Math.round(((this.displayedPeak * inspTime + setPeep * expTime) / cycleDuration) * 10) / 10,
      peepTotal: Math.round(peepTotal * 10) / 10,
      autoPeep: autoPeepCalc,
      drivingPressure: Math.max(0, Math.round((this.displayedPlat - peepTotal) * 10) / 10),
      vte: Math.round(this.displayedVte),
      vti: Math.round(this.displayedVti),
      minuteVolume: Math.round(this.displayedMV * 10) / 10,
      spontaneousMinuteVolume: Math.round((this.displayedMV * (patient.spontaneousDrive ? 0.4 : 0)) * 10) / 10,
      leakVolume: Math.round(this.displayedVti - this.displayedVte),
      totalRate: measuredRR,
      spontaneousRate: patient.spontaneousDrive ? Math.round(dynamicSpontRate) : 0,
      mandatoryRate: targetRR,
      inspiratoryTime: Math.round(inspTime * 100) / 100,
      expiratoryTime: Math.round(expTime * 100) / 100,
      ieRatioString,
      staticCompliance: Math.round(this.displayedVte / Math.max(1, (this.displayedPlat - peepTotal))),
      dynamicCompliance: Math.round(this.displayedVte / Math.max(1, (this.displayedPeak - peepTotal))),
      airwayResistance: Math.round(Raw * 10) / 10,
      timeConstant: Math.round(tau * 100) / 100,
      rapidShallowBreathingIndex: Math.round(measuredRR / (Math.max(1, this.displayedVte) / 1000)),
      mechanicalPower: Math.round(0.098 * measuredRR * (this.displayedVte / 1000) * (this.displayedPeak - (this.displayedPlat - peepTotal) / 2)),
      vtPerKgIBW: Math.round((this.displayedVte / patient.idealBodyWeightKg) * 10) / 10,
      pao2: Math.round(this.currentPaO2),
      paco2: Math.round(this.currentPaCO2),
      ph: this.currentpH,
      hco3,
      baseExcess: smoothedBaseExcess,
      spo2: Math.round(this.currentSpO2),
      pfRatio: smoothedPfRatio,
      alveolarPaO2: Math.round(pAlveolarO2),
      aaGradient: Math.max(5, Math.round(pAlveolarO2 - this.currentPaO2)),
      etco2: smoothedEtCO2,
    };

    return { sample, monitored };
  }
}

export const physicsEngine = new VentilationPhysicsEngine();
